/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUserRouteImport } from './routes/_dashboard/user'
import { Route as DashboardIncidentRouteImport } from './routes/_dashboard/incident'
import { Route as DashboardContractRouteImport } from './routes/_dashboard/contract'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIncidentRoute = DashboardIncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractRoute = DashboardContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof DashboardContractRoute
  '/incident': typeof DashboardIncidentRoute
  '/user': typeof DashboardUserRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/contract': typeof DashboardContractRoute
  '/incident': typeof DashboardIncidentRoute
  '/user': typeof DashboardUserRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/contract': typeof DashboardContractRoute
  '/_dashboard/incident': typeof DashboardIncidentRoute
  '/_dashboard/user': typeof DashboardUserRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/contract' | '/incident' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/contract' | '/incident' | '/user' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/contract'
    | '/_dashboard/incident'
    | '/_dashboard/user'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/user': {
      id: '/_dashboard/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/incident': {
      id: '/_dashboard/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof DashboardIncidentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/contract': {
      id: '/_dashboard/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof DashboardContractRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardContractRoute: typeof DashboardContractRoute
  DashboardIncidentRoute: typeof DashboardIncidentRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContractRoute: DashboardContractRoute,
  DashboardIncidentRoute: DashboardIncidentRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
